name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: Which environment to use
        options:
        - prod-<rh, mot>
        - <dev-rh, staging-mot>
jobs:
  deploy:
    name: Rollback Production
    uses: careem/shared-workflows/.github/workflows/devx.yml@master
    secrets: inherit
    with:
      service-name: ${{ vars.SERVICE_NAME }}
      env: prod
      profile: ${{inputs.profile}}
      action: rollback
